pin `chrono` to fix weird build error
```
[mhueschen@vayu:~/projects/widgets_rs]$ npm run paperz:build

> paperz:build
> cargo build -p paperz --release --target wasm32-unknown-unknown && cp $CARGO_TARGET_DIR/wasm32-unknown-unknown/release/paperz.wasm ./happs/paperz

    Finished release [optimized] target(s) in 0.05s

[mhueschen@vayu:~/projects/widgets_rs]$ npm run paperz:pack

> paperz:pack
> hc dna pack happs/paperz && hc app pack happs/paperz

Wrote bundle /home/mhueschen/projects/widgets_rs/happs/paperz/paperz.dna
Wrote bundle /home/mhueschen/projects/widgets_rs/happs/paperz/paperz.happ

vayu :: ~/projects/widgets_rs ‹main› » npm run paperz:run

> paperz:run
> hc sandbox generate happs/paperz && WASM_LOG=debug RUST_LOG=error RUST_BACKTRACE=full hc sandbox -f=9000 run -l -p 9999

hc-sandbox: Creating 1 conductor sandboxes with same settings
hc-sandbox: Config ConductorConfig { environment_path: DatabaseRootPath("/tmp/OYCgC6gKwl8Mh1dVdcAel"), keystore: LairServerLegacyDeprecated { keystore_path: Some("/tmp/OYCgC6gKwl8Mh1dVdcAel/keystore"), danger_passphrase_insecure_from_config: "default-insecure-passphrase" }, dpki: None, admin_interfaces: Some([AdminInterfaceConfig { driver: Websocket { port: 0 } }]), network: None, db_sync_strategy: Fast }
hc-sandbox: Created directory at: /tmp/OYCgC6gKwl8Mh1dVdcAel Keep this path to rerun the same sandbox
hc-sandbox: Created config at /tmp/OYCgC6gKwl8Mh1dVdcAel/conductor-config.yaml
Aug 15 17:41:27.492 ERROR lair_keystore_client: error=IpcClientConnectError("/tmp/OYCgC6gKwl8Mh1dVdcAel/keystore/socket", Os { code: 2, kind: NotFound, message: "No such file or directory" }) file="/build/cargo-vendor-dir/lair_keystore_client-0.0.10/src/lib.rs" line=41

Conductor ready.
Error: Failed to install app: Expected AdminResponse::AppBundleInstalled but got Error(InternalError("Conductor returned an error while using a ConductorApi: EntryDefStoreError(DnaError(WasmError(Compile(\"Error while importing \\\"__wbindgen_placeholder__\\\".\\\"__wbindgen_describe\\\": unknown import. Expected Function(FunctionType { params: [I32], results: [] })\"))))"))
```

fixed by adding a pin on `chrono` b/c for some reason newer versions of it introduce a dep on `wasm-bindgen` which leakes thru to us?